### PR TITLE
add industry in `/data-holders/brands` response

### PR DESCRIPTION
**Pull request by jithin-sukumar**
## What
Add industry in `/data-holders/brands` response

## Why
According to current [API doc](https://cdr-register.github.io/register/#tocSresponseregisterdataholderbrandlist), `industry` should be included in the response of `/{industry}/data-holders/brands` endpoint.

## Results

<details>
<summary><b>Before</b></summary>

```sh-session
$ curl --location --request GET 'https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page-size=1' --header 'x-v: 1' --header 'Authorization: Bearer $ACCESS_TOKEN'
{
    "data": [
        {
            "dataHolderBrandId": "804fc2fb-18a7-4235-9a49-2af393d18bc7",
            "brandName": "Bank Brand 1",
            "logoUri": "https://bank1/img/logo.png",
            "legalEntity": {
                "legalEntityId": "0d332caa-8cd8-4ac9-8898-20641c54bc8c",
                "legalEntityName": "Bank Legal Entity 1",
                "logoUri": "https://bank/logo.png",
                "registrationNumber": null,
                "registrationDate": null,
                "registeredCountry": null,
                "abn": "11111111111",
                "acn": "888777666",
                "arbn": null,
                "industryCode": null,
                "organisationType": null
            },
            "status": "ACTIVE",
            "endPointDetail": {
                "version": "1",
                "publicBaseUri": "https://publicapi.bank1",
                "resourceBaseUri": "https://api.bank1",
                "infosecBaseUri": "https://idp.bank1",
                "extensionBaseUri": "",
                "websiteUri": "https://bank1/"
            },
            "authDetails": [
                {
                    "registerUType": "SIGNED-JWT",
                    "jwksEndpoint": "https://idp.bank1/jwks"
                }
            ],
            "lastUpdated": "2021-04-06T11:58:00Z"
        }
    ],
    "links": {
        "first": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=1&page-size=1",
        "last": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=30&page-size=1",
        "next": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=2&page-size=1",
        "prev": null,
        "self": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page-size=1"
    },
    "meta": {
        "totalRecords": 30,
        "totalPages": 30
    }
}
```

</details>

<details>
<summary><b>After</b></summary>

```sh-session
$ curl --location --request GET 'https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page-size=1' --header 'x-v: 1' --header 'Authorization: Bearer $ACCESS_TOKEN'
{
    "data": [
        {
            "dataHolderBrandId": "804fc2fb-18a7-4235-9a49-2af393d18bc7",
            "brandName": "Bank Brand 1",
            "industry": "banking",
            "logoUri": "https://bank1/img/logo.png",
            "legalEntity": {
                "legalEntityId": "0d332caa-8cd8-4ac9-8898-20641c54bc8c",
                "legalEntityName": "Bank Legal Entity 1",
                "logoUri": "https://bank/logo.png",
                "registrationNumber": null,
                "registrationDate": null,
                "registeredCountry": null,
                "abn": "11111111111",
                "acn": "888777666",
                "arbn": null,
                "industryCode": null,
                "organisationType": null
            },
            "status": "ACTIVE",
            "endPointDetail": {
                "version": "1",
                "publicBaseUri": "https://publicapi.bank1",
                "resourceBaseUri": "https://api.bank1",
                "infosecBaseUri": "https://idp.bank1",
                "extensionBaseUri": "",
                "websiteUri": "https://bank1/"
            },
            "authDetails": [
                {
                    "registerUType": "SIGNED-JWT",
                    "jwksEndpoint": "https://idp.bank1/jwks"
                }
            ],
            "lastUpdated": "2021-04-06T11:58:00Z"
        }
    ],
    "links": {
        "first": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=1&page-size=1",
        "last": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=30&page-size=1",
        "next": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page=2&page-size=1",
        "prev": null,
        "self": "https://localhost:7001/cdr-register/v1/banking/data-holders/brands?page-size=1"
    },
    "meta": {
        "totalRecords": 30,
        "totalPages": 30
    }
}
```

</details>

### CODE REVIEW

**Comment by ACCC-DF** [comment]
@jithin97 - thanks very much for identifying, fixing this issue and submitting the PR.

I needed to make a couple of changes in order to get the solution to compile and the integration tests to pass.

In the `GetDataHolderBrands_Tests` could you make the following changes in the `GetExpectedResponse` method please:

```
           var data = allData
                .OrderBy(brand => brand.BrandName).ThenBy(brand => brand.BrandId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .Select(brand => new
                {
                    dataHolderBrandId = brand.BrandId,
                    brandName = brand.BrandName,
                    // CHANGE: Add the following line:
                    industry = brand.Participation.Industry.IndustryTypeCode,
                    logoUri = brand.LogoUri,
                    legalEntity = new
                    {
                        legalEntityId = brand.Participation.LegalEntity.LegalEntityId,
                        legalEntityName = brand.Participation.LegalEntity.LegalEntityName,
                        // CHANGE: Remove the following line:
                        //industry = brand.DataHolder.Industry,
                        logoUri = brand.Participation.LegalEntity.LogoUri,
```

Thanks again for taking the time to submit the PR.  We really appreciate it!

**Comment by jithin97** [comment]
@CDR-DF Thanks for the comment. I misplaced it 😅 
I fixed it now! :)

**Comment by jithin-sukumar** [comment]
@CDR-DF Thanks for the comment. I misplaced it 😅
I fixed it now! :)

**Review by ACCC-DF — APPROVED** [review]
Looks good.  Reviewed ok.

Thanks for submitting!

**Pull request merged**
